### ISSUE TITLE
Server URL, Webhook URL?

### ISSUE THREAD

**Issue by conkydong** [crobibero/jellyfin-plugin-webhook#1]
What do I have to fill in those fields? Server URL is my Jellyfin URL, right? In my case that would be „http://omv:8096“.
What do I have to fill in for Webhook URL?

**Comment by conkydong** [comment]
Figured it out.
1. Yes
2. Yes

**Comment by zpengcom** [comment]
Server URL is my Jellyfin URL?? I tried it and it doesn't seem to work
