### ISSUE TITLE
[Feature request] Ability to send all raw data to Generic Destination

### ISSUE THREAD

**Issue by oscargarciablazquez** [crobibero/jellyfin-plugin-webhook#11]
Right now I can do this with a template including all possible variables, but I would have to update it any time you add or remove properties from the plugin, so it would be perfect to have the ability directly implemented in the plugin.
Maybe with a "Send All" checkbox above the "Template" text box?

**Comment by crobibero** [comment]
Will look into this when I have a chance, good suggestion!

**Comment by crobibero** [comment]
Added in version `2.2021.304.228`
