### ISSUE TITLE
[Movie/TV Show] "Has been added to Jellfin Server"

### ISSUE THREAD

**Issue by matda59** [crobibero/jellyfin-plugin-webhook#16]
when you choose "Playback Start" notification - gotify indicates that a movie or TV show has been added to the Jellyfin Server instead of informing you that a certain user is watching a movie

![image](https://user-images.githubusercontent.com/27712001/111148873-431bdc80-85e0-11eb-9743-0e69db934841.png)

**Comment by crobibero** [comment]
I assume you're using the template I provided. The plugin outputs exactly what you tell it to. If you want to change the message you have to actually change the template. I just provided a sample to get people started.

The following is the "title" of the message:
```
{{else}}
        {{#if_equals ItemType 'Episode'}}
            "title": "{{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} {{{Name}}} has been added to {{{ServerName}}}"
        {{else}}
            "title": "{{{Name}}} ({{Year}}) has been added to {{{ServerName}}}"
        {{/if_equals}}
    {{/if_equals}}
```

**Comment by crobibero** [comment]
One thing you could change `title` to is
```
"title": "{{{Username}}} has started playing {{{Name}}}"
```

This is just a basic example, but you should be able to use it as a baseline

**Comment by matda59** [comment]
Perfect. Worked a treat.

            "title": "{{{Username}}} has started playing {{{Name}}} ({{Year}})"
