### ISSUE TITLE
Adding annotation on destinations

### ISSUE THREAD

**Issue by EVOTk** [crobibero/jellyfin-plugin-webhook#19]
Hello,
For notifications via Gotify, if you want to organize it properly (personalization of the message, users, ...) it forces you to make several identical "Destination", but with different options.

Unfortunately, it is not possible to differentiate them quickly:
![](https://i.imgur.com/d2vSvoH.png)

Do you think that it is possible to include the possibility of making a "note" to customize the title of the "Destination", for example:
![](https://i.imgur.com/NYNEWck.png)

Thank you

**Comment by crobibero** [comment]
Hah good point, I will look into adding some some of name/description when I have some time

**Comment by EVOTk** [comment]
Big thx :)
