### ISSUE TITLE
Thumbnail possible?

### ISSUE THREAD

**Issue by conkydong** [crobibero/jellyfin-plugin-webhook#2]
Gotify doesn't show the thumbnails, did I do something wrong?

**Comment by crobibero** [comment]
Please post your template so I can take a look

**Comment by conkydong** [comment]
I just used your example.

**Comment by crobibero** [comment]
It looks like you used an internal (docker?) domain when configuring. The domain needs to be publicly accessible, or if you only care about getting notifications in network you can use the internal ip.


In future versions I might add image proxying, but right now it just uses the Jellyfin endpoint.

**Comment by conkydong** [comment]
Yes, Jellyfin is running in a docker container. That means I have to use the IP address of my server? And yes, I Just want to use notifications in my network.

**Comment by crobibero** [comment]
Yes, use the IP of your server (or whatever IP you use to access Jellyfin)

**Comment by conkydong** [comment]
So the hostname (in my case "omv") isn't working, so I have to use the IP address instead.
