### ISSUE TITLE
Send All Properties (ignores template) option in Gotify not working

### ISSUE THREAD

**Issue by Tezonis** [crobibero/jellyfin-plugin-webhook#21]
Hi,

**Send All Properties (ignores template)** option in Gotify Destination is not working, there is this error message in Jellyfin logs:

> [22:57:36] [WRN] [455] Jellyfin.Plugin.Webhook.Destinations.Gotify.GotifyClient: Error sending notification: {"error":"Bad Request","errorCode":400,"errorDescription":"json: cannot unmarshal string into Go struct field MessageExternal.id of type uint"}

It's working with the option is disabled (and using your provided template for example).

Thank you for this plugin ;)

**Comment by crobibero** [comment]
I wouldn’t expect that to work, as it send an object that isn’t compatible with Gotify’s api. The send all properties is really only useful for testers such as https://webhook.site

**Comment by Tezonis** [comment]
Ok, thank you for making me discover this handy web site :)

I ended up with this very simple template below:
```handlebars
{
    "extras":{
        "client::display": {
            "contentType": "text/markdown"
        }
    },
    "priority": {{Priority}},
    "title": "Jellyfin event",
    "message": "{{{Name}}}"
}
```

If any one is interrested, it catches all the "Generic" notifications (Jellyfin's default ones).
Other notifications are interresting too but need a proper case for each of them in the template, it's lot of work.
By any chance, do you know someone who did it for every existing notifications? :)
Maybe I will motivate myself to to it one day.
