### ISSUE TITLE
[Request] Webhook to Telegram

### ISSUE THREAD

**Issue by xiNeRoar** [crobibero/jellyfin-plugin-webhook#27]
Dear devs,

Will there be any support to telegram bot or channel in foreseeable future?
I have tried a lot to figure out a way to connect with telegram but couldn't succeed.
Please consider to include telegram in your webhook plugin too >.<

**Comment by crobibero** [comment]
I just connected the webhook plugin without issue. Sample for "Item Added":
1. Create a bot
2. https://api.telegram.org/bot{access_token}/sendPhoto
3. Body - this will send the poster with a caption "Item added to Jellyfin":
```
{
  "chat_id": insert_chat_id_here,
  "photo": "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary",
{{#if_equals ItemType 'Season'}}
	"caption": "{{{SeriesName}}} {{{Name}}} has been added to {{{ServerName}}}"
{{else}}
	{{#if_equals ItemType 'Episode'}}
		"caption": "{{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} {{{Name}}} has been added to {{{ServerName}}}"
	{{else}}
		"caption": "{{{Name}}} ({{Year}}) has been added to {{{ServerName}}}"
	{{/if_equals}}
{{/if_equals}}
}
```

**Comment by xiNeRoar** [comment]
Dear devs,

Sorry to bother, may i know what should i type in to this field?
![webhook](https://user-images.githubusercontent.com/66216186/116955393-fcd02900-acc4-11eb-8cee-7270d89a3a9f.JPG)
or how should i get it work? i am not so familiar with the code you paste. May i know where should i paste them to?
Thank you very much for your patience.

**Comment by crobibero** [comment]
You put the link from 2, replacing {access_token} with your bots access token.

**Comment by xiNeRoar** [comment]
Thank you crobibero!
And then i put below in "Template" field?
```
{
  "chat_id": insert_chat_id_here,
  "photo": "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary",
{{#if_equals ItemType 'Season'}}
	"caption": "{{{SeriesName}}} {{{Name}}} has been added to {{{ServerName}}}"
{{else}}
	{{#if_equals ItemType 'Episode'}}
		"caption": "{{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} {{{Name}}} has been added to {{{ServerName}}}"
	{{else}}
		"caption": "{{{Name}}} ({{Year}}) has been added to {{{ServerName}}}"
	{{/if_equals}}
{{/if_equals}}
}
```

**Comment by crobibero** [comment]
Yes, replacing `insert_chat_id_here` with the chat that you want the messages to go to. 

You can use this to get the chat id: https://stackoverflow.com/a/33862907

**Comment by xiNeRoar** [comment]
Thank you very much!
So i can customize the message in;
```
"caption": "{{{SeriesName}}} {{{Name}}} has been added to {{{ServerName}}}"
```
with markdown syntax, am i correct?

**Comment by crobibero** [comment]
I don’t know the capabilities of the Telegram api, I just got it working to confirm that it was possible

**Comment by xiNeRoar** [comment]
totally understand, thank you again for all the efforts :D

**Comment by ClankJake** [comment]
hello @crobibero. I copied this template but I'm getting this error:
[2021-05-04 11: 36: 17.949 -03: 00] [WRN] Error sending notification: "{\" ok \ ": false, \" error_code \ ": 400, \" description \ ": \" Bad Request: there is no photo in the request \ "}"

When I add new content.

**Comment by crobibero** [comment]
Please edit `logging.default.json`, add `"Jellyfin.Plugin.Webhook": "Debug"` to the overrides list (make sure to add a comma after `"System": "Warning"`, then upload the log after trying to send another notification.

**Comment by ClankJake** [comment]
@crobibero I put this line but there was no change, no log keeps showing me the same thing

**Comment by xiNeRoar** [comment]
```
{
  "chat_id": insert_chat_id_here,
  "photo": "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary",
{{#if_equals ItemType 'Season'}}
	"caption": "{{{SeriesName}}} {{{Name}}} has been added to {{{ServerName}}}"
{{else}}
	{{#if_equals ItemType 'Episode'}}
		"caption": "{{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} {{{Name}}} has been added to {{{ServerName}}}"
	{{else}}
		"caption": "{{{Name}}} ({{Year}}) has been added to {{{ServerName}}}"
	{{/if_equals}}
{{/if_equals}}
}
```

Sorry to bother...is this template only work for TV shows since it contain "SeriesName" & "Episode" ? How can i edit it to work for movie? And..is there anyway i can customize the template content? sorry to ask such newbie questions...

**Comment by crobibero** [comment]
This block here
```
	{{else}}
		"caption": "{{{Name}}} ({{Year}}) has been added to {{{ServerName}}}"
	{{/if_equals}}
```

is for things that aren't `Season` or `Episode`.
You can customize the template as much as you want, the template is just a sample to give you an idea of what to enter

**Comment by ClankJake** [comment]
@crobibero mine is showing this error when activating the debug:
[2021-05-21 17:15:04.459 -03:00] [DBG] [37] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: SendAsync Body: "{
  \"chat_id\": -1001xxxxxxxx,
  \"photo\": \"xxx.xxx.249.xxx:xxxx/Items/f014b517-1780-8b68-cbf0-1d82ee375b72/Images/Primary\",
		\"caption\": \"Phineas e Ferb (2007) has been added to Jellyfin Server\"
}"
[2021-05-21 17:15:04.563 -03:00] [WRN] [37] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Error sending notification: "{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: there is no photo in the request\"}"

**Comment by crobibero** [comment]
The photo url needs to be publicly accessible for Telegram to be able to use it. Silly limitation but I ran into the same issue when testing.

**Comment by xiNeRoar** [comment]
> The photo url needs to be publicly accessible for Telegram to be able to use it. Silly limitation but I ran into the same issue when testing.

Isn't ClankJake's url not publicly accessible for telegram?

**Comment by crobibero** [comment]
No idea, all I see is 1 part of the full IP address. All I can comment is the moment I used my domain instead of my local debug copy sending images worked

**Comment by ClankJake** [comment]
Here is the image that was a problem too.
https://play.ckcloud.tk/Items/2559d1692e05f68c53440cb1c59e6e85/Images/Primary

But when doing the procedure by naveagor it goes well only by the plugin is giving this error above

**Comment by xiNeRoar** [comment]
> Here is the image that was a problem too.
> https://play.ckcloud.tk/Items/2559d1692e05f68c53440cb1c59e6e85/Images/Primary
> 
> But when doing the procedure by naveagor it goes well only by the plugin is giving this error above

same here. i am also using this link as an image source but it does not grab by telegram don't know why

**Comment by ClankJake** [comment]
@xiNeRoar I also wanted to understand why. tested by overseerr the webhook it works normally takes good image

**Comment by xiNeRoar** [comment]
@ClankJake did you find any workaround to send notification to telegram upon item added?
I am currently stucked and find no way to achieve this. I have try notification via radarr, ombi, jellyfin
But none of them is fully workable. Or i am not able to make them fully workable.
Ombi is the one almost achieved when i want, but it is won't notify upon item added to jellyfin, it send notification when request on ombi had been fulfilled, which left those item added to jellyfin manually or by list no notification.

**Comment by ClankJake** [comment]
I'm using a Telegram notification plugin but only in text mode I wanted something more personalized like this plugin

**Comment by Tuetenk0pp** [comment]
Hello, where can I find the exact message, the plugin sends to the Telegram API? I tried to test it but the exact same json that I also send with curl produces an error with the plugin.

Here's some details:

### curl
``` bash
curl -X POST \
-H 'Content-Type: application/json' \
-d '{"chat_id": "CHAT_ID","text":"This is a test using curl","disable_notification":"true","protect_content":"true"}' \
https://api.telegram.org/botBOT_TOKEN/sendMessage
```

### Generic Destination

``Webhook Url: https://api.telegram.org/botBOT_TOKEN/sendMessage``
``Checkboxes: Authentication, Playback``
``` json
{"chat_id":"CHAT_ID","text":"This is a test using Jellyfin","disable_notification":"true","protect_content":"true"}
```

This gives the following error:
``` log
[09:40:31] [DBG] [27] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: SendAsync Body: {"chat_id":"CHAT_ID","text":"This is a test using Jellyfin","disable_notification":"true","protect_content":"true"}
[09:40:31] [WRN] [27] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with POST request to https://api.telegram.org/botBOT_TOKEN/sendMessage: {"chat_id":"CHAT_ID","text":"This is a test using Jellyfin","disable_notification":"true","protect_content":"true"}
[09:40:31] [WRN] [27] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with response status code BadRequest: {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}
```

**Comment by crobibero** [comment]
Its been a while since I used the telegram API, but try adding `Content-Type` `application/json` as a header

**Comment by Tuetenk0pp** [comment]
Thank you so much! That totally did it!

**Comment by Fallenbagel** [comment]
> I just connected the webhook plugin without issue. Sample for "Item Added":
> 
> 1. Create a bot
> 2. [https://api.telegram.org/bot{access_token}/sendPhoto](https://api.telegram.org/bot%7Baccess_token%7D/sendPhoto)
> 3. Body - this will send the poster with a caption "Item added to Jellyfin":
> 
> ```
> {
>   "chat_id": insert_chat_id_here,
>   "photo": "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary",
> {{#if_equals ItemType 'Season'}}
> 	"caption": "{{{SeriesName}}} {{{Name}}} has been added to {{{ServerName}}}"
> {{else}}
> 	{{#if_equals ItemType 'Episode'}}
> 		"caption": "{{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} {{{Name}}} has been added to {{{ServerName}}}"
> 	{{else}}
> 		"caption": "{{{Name}}} ({{Year}}) has been added to {{{ServerName}}}"
> 	{{/if_equals}}
> {{/if_equals}}
> }
> ```

I tried this and I got it working as a sendMessage but when I use it as sendPhoto it only works for series and episodes when it goes to Movies I get this error
`[WRN] [61] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with POST request to https://api.telegram.org/bot[token]/sendPhoto: {"chat_id":"chatid",
    "photo": "https://url/Items/itemcode/Images/Primary",
       "caption": "<b>Movie Now Available</b>\n\n<b>Eternals (2021)</b>\nThe Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind&#8217;s most ancient enemy, the Deviants.\n\n<b>Runtime</b>\n02:35:48\n\n<b>Status</b>\nAvailable"
"parse_mode": "html",
"disable_notification":"true","protect_content":"true"
}
[15:33:21] [WRN] [61] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with response status code BadRequest: {"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}`

Here's what I have been using
```
{"chat_id":"chatid",
    "photo": "https://serverurl/Items/{{ItemId}}/Images/Primary",
   {{#if_equals ItemType 'Season'}}
       "caption": "<b>Series Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
   {{else}}
       {{#if_equals ItemType 'Episode'}}
           "caption": "<b>Episode Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b>S{{SeasonNumber00}}E{{EpisodeNumber00}}</b> - <b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
       {{else}}
       {{else}}
       "caption": "<b>Movie Now Available</b>\n\n<b>{{{Name}}} ({{Year}})</b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
   {{/if_equals}}
{{/if_equals}},
"parse_mode": "html",
"disable_notification":"true","protect_content":"true"
}
``` 

with the header `key:Content-Type` and `Value:application/json`.

Why is it when i use the sendPhoto api it doesn't work but when i use the sendMessage api it does?

**Comment by lyaschuchenko** [comment]
Tried many times, but notification not worked.

**Comment by Tuetenk0pp** [comment]
You have this line twice in your config, @Fallenbagel:

> ```json
>    {{else}}
>    {{else}}
> ```

**Comment by Fallenbagel** [comment]
> You have this line twice in your config, @Fallenbagel:
> 
> > ```json
> >    {{else}}
> >    {{else}}
> > ```

Yeah I figured out back then and been using this for almost half an year now c:

@lyaschuchenko I PRd a template for telegram with instructions. Could you try that? It's in the template folder

**Comment by lyaschuchenko** [comment]
@Fallenbagel now working, i fix it

**Comment by itsboo07** [comment]
Hi... What should be the server url in webhook? My jellyfin server url is http://192.168.0.200:8083
![Screenshot_2022-10-04-02-23-05-855_com kiwibrowser browser](https://user-images.githubusercontent.com/87331871/193680316-92b2729c-233b-49ce-9829-ff5d53c53145.png)

**Comment by lyaschuchenko** [comment]
> Hi... What should be the server url in webhook? My jellyfin server url is http://192.168.0.200:8083 is it the same? I tried but didnot work ![Screenshot_2022-10-04-02-23-05-855_com kiwibrowser browser](https://user-images.githubusercontent.com/87331871/193680316-92b2729c-233b-49ce-9829-ff5d53c53145.png)

use TLD domain, such as `my.jelly.net` for example

**Comment by lyaschuchenko** [comment]
For me, its variant work perfectly
```
{
  "chat_id": "-x",
   "photo": "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary",
{{#if_equals ItemType 'Season'}}
  "caption": "Серіал {{{SeriesName}}} {{{Name}}} був доданий на {{{ServerName}}}\n{{Overview}}\n\n<b>Тривалість</b>\n{{RunTime}}"
{{else}}
  {{#if_equals ItemType 'Episode'}}
    "caption": "Серія {{{SeriesName}}} S{{SeasonNumber00}}E{{EpisodeNumber00}} {{{Name}}} була додана на {{{ServerName}}}\n{{Overview}}\n\n<b>Тривалість</b>\n{{RunTime}}"
  {{else}}
{{#if_equals ItemType 'MusicAlbum'}}
    "caption": "Альбом {{{Artist}}} {{{Name}}} {{{Year}}} був доданий на {{{ServerName}}}"
    {{/if_equals}}
{{else}}
   "caption": "{{{Name}}} ({{Year}}) був доданий на {{{ServerName}}}\n{{Overview}}\n\n<b>Тривалість</b>\n{{RunTime}}"
{{/if_equals}}
{{/if_equals}}
"disable_notification": "true", "protect_content": "true",
}
```
and don`t forget add Content-Type/application-json

**Comment by EGUltraTM** [comment]
Is it not working maybe cause i dont use a TLD. I only use the ip. WIth browser test if the bot code and channel id is correct it works to send an message. But never get one when uploading a movie for example and hes adding it. I see its added but nothing more.

**Comment by Kuli222** [comment]
Hi, I need some help. I've tried a few different things, but can't get it to work. I'm trying to get a text message sent when a movie starts, stops, resumes and pauses to telegram. To control lights through homey. I don't know what the template should look like for that function.

**Comment by gomaaz** [comment]
I spend hours to be clarified about the Chat ID.
Note: if your chat id is 12345678 then you need to prefix it with -100 such that it is -10012345678. 

Example:
"chat_id": "-10012345678"

**Comment by lyaschuchenko** [comment]
> I spend hours to be clarified about the Chat ID. Note: if your chat id is 12345678 then you need to prefix it with -100 such that it is -10012345678.
> 
> Example: "chat_id": "-10012345678"

" - " - is for private chat/channel

**Comment by 101jul** [comment]
I am getting the same Error: 
`
[2023-08-16 18:19:38.319 +02:00] [WRN] [24] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with "POST" request to https://api.telegram.org/bot645*********3:AAFgaBW*******ZZsxw6r3-Ys/sendPhoto: "{\"chat_id\":\"\",   
\"photo\":\"www.******.de/Items/003a4f7c-a157-a688-c36b-6f0c5f1eb5c1/Images/Primary\",
       \"caption\": \"<b>Movie Now Available</b>\n\n<b>Insidious: The Last Key (2018)</b>\nParapsychologin Elise Rainier wohnt mittlerweile ... der Verdammnis anheimfallen&#160;&#8230;\n\n<b>Runtime</b>\n01:43:24\n\n<b>Status</b>\nAvailable\"
,
\"parse_mode\": \"html\",
\"disable_notification\":\"true\",\"protect_content\":\"true\"
}"
[2023-08-16 18:19:38.319 +02:00] [WRN] [24] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with response status code BadRequest: "{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: there is no photo in the request\"}"
`
It states that there is no image. However, if you access the link directly: 'www.******.de/Items/003a4f7c-a157-a688-c36b-6f0c5f1eb5c1/Images/Primary,' the image loads perfectly fine and is publicly reachable. 
What am I missing? Any tips?

**Comment by gomaaz** [comment]
> I am getting the same Error: `[2023-08-16 18:19:38.319 +02:00] [WRN] [24] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with "POST" request to https://api.telegram.org/bot645*********3:AAFgaBW*******ZZsxw6r3-Ys/sendPhoto: "{\"chat_id\":\"\", \"photo\":\"www.******.de/Items/003a4f7c-a157-a688-c36b-6f0c5f1eb5c1/Images/Primary\", \"caption\": \"<b>Movie Now Available</b>\n\n<b>Insidious: The Last Key (2018)</b>\nParapsychologin Elise Rainier wohnt mittlerweile ... der Verdammnis anheimfallen&#160;&#8230;\n\n<b>Runtime</b>\n01:43:24\n\n<b>Status</b>\nAvailable\" , \"parse_mode\": \"html\", \"disable_notification\":\"true\",\"protect_content\":\"true\" }" [2023-08-16 18:19:38.319 +02:00] [WRN] [24] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with response status code BadRequest: "{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: there is no photo in the request\"}"` It states that there is no image. However, if you access the link directly: 'www.******.de/Items/003a4f7c-a157-a688-c36b-6f0c5f1eb5c1/Images/Primary,' the image loads perfectly fine and is publicly reachable. What am I missing? Any tips?

can you post your template config please?

**Comment by 101jul** [comment]
> > I am getting the same Error: `[2023-08-16 18:19:38.319 +02:00] [WRN] [24] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with "POST" request to https://api.telegram.org/bot645*********3:AAFgaBW*******ZZsxw6r3-Ys/sendPhoto: "{\"chat_id\":\"\", \"photo\":\"www.******.de/Items/003a4f7c-a157-a688-c36b-6f0c5f1eb5c1/Images/Primary\", \"caption\": \"<b>Movie Now Available</b>\n\n<b>Insidious: The Last Key (2018)</b>\nParapsychologin Elise Rainier wohnt mittlerweile ... der Verdammnis anheimfallen&#160;&#8230;\n\n<b>Runtime</b>\n01:43:24\n\n<b>Status</b>\nAvailable\" , \"parse_mode\": \"html\", \"disable_notification\":\"true\",\"protect_content\":\"true\" }" [2023-08-16 18:19:38.319 +02:00] [WRN] [24] Jellyfin.Plugin.Webhook.Destinations.Generic.GenericClient: Notification failed with response status code BadRequest: "{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: there is no photo in the request\"}"` It states that there is no image. However, if you access the link directly: 'www.******.de/Items/003a4f7c-a157-a688-c36b-6f0c5f1eb5c1/Images/Primary,' the image loads perfectly fine and is publicly reachable. What am I missing? Any tips?
> 
> can you post your template config please?

{"chat_id":"{{-962****556}}",   
"photo":"{{ServerUrl}}/Items/{{ItemId}}/Images/Primary",
   {{#if_equals ItemType 'Season'}}
       "caption": "<b>{{ItemType}} Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
   {{else}}
       {{#if_equals ItemType 'Episode'}}
           "caption": "<b>Episode Now Available</b>\n\n<b>{{{SeriesName}}} ({{Year}})</b>\n<b>S{{SeasonNumber00}}E{{EpisodeNumber00}}</b> - <b><em>{{{Name}}}</em></b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
    {{else}}
       "caption": "<b>{{ItemType}} Now Available</b>\n\n<b>{{{Name}}} ({{Year}})</b>\n{{Overview}}\n\n<b>Runtime</b>\n{{RunTime}}\n\n<b>Status</b>\nAvailable"
   {{/if_equals}}
{{/if_equals}},
"parse_mode": "html",
"disable_notification":"true","protect_content":"true"
}

**Comment by gomaaz** [comment]
Consider the following  in your script:

"chat_id": "-962****556",
instead of 
"chat_id":"{{-962****556}}",

try to set the Server URL beginning with "https://...."

**Comment by 101jul** [comment]
The error still persists. I am still receiving the message:

BadRequest: "{"ok":false,"error_code":400,"description":"Bad Request: there is no photo in the request"}"

I have used both the internal IP and the external domain. I have read multiple times that an externally reachable domain should be provided. But does that even make sense? The image is being attached internally, right? So, the server accesses the path, retrieves the image, and sends it. Therefore, I have ensured that the address is reachable internally by the server. Unfortunately, I am still encountering the error.

Any help is welcome :D

**Comment by cryptolukas** [comment]
I'm trying to use this [example](https://github.com/jellyfin/jellyfin-plugin-webhook/blob/master/Jellyfin.Plugin.Webhook/Templates/Telegram.handlebars) and it is still failing with the following error.
Can someone give me a hint how to resolve it?
```
Notification failed with response status code BadRequest: {"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}
```

**Comment by jozemanue** [comment]
i have the same problem. appears the error "Bad Request: failed to get HTTP URL content".

**Comment by jahlib** [comment]
> i have the same problem. appears the error "Bad Request: failed to get HTTP URL content".

I have an answer why it happens - https://github.com/jellyfin/jellyfin-plugin-webhook/issues/204
