### ISSUE TITLE
Can't get the Gotify Destination to authenticate

### ISSUE THREAD

**Issue by scrafiiii** [crobibero/jellyfin-plugin-webhook#28]
Hi,

I can't get the Gotify Destination to authenticate, I always get the following Error Message:

`[2021-04-24 10:53:10.507 +02:00] [WRN] [58] Jellyfin.Plugin.Webhook.Destinations.Gotify.GotifyClient: Error sending notification: "{\"error\":\"Unauthorized\",\"errorCode\":401,\"errorDescription\":\"you need to provide a valid access token or user credentials to access this api\"}"`

I've tried now different configuration with the Webhook URL and token fields:

```
https://gotify.mydomain.de/message?token=ABCDEFGTOKEN
https://gotify.mydomain.de/message?token= #Token is present in the token configuration field
https://gotify.mydomain.de/message #Token is present in the token configuration field
```

But whatever I do I get the same error message, but I can confirm that the Webhook itself and the Token should be valid if I run a curl from the cli (I changed my domain and the Token) it works flawlessly

`curl "https://gotify.mydomain.de/message?token=ABCDEFGTOKEN" -F"title=my title" -F "message=my message" -F "priority=5"`

I'm using Version 2.2021.409.38 from the Webhook Plugin and JellyFin Server version 10.7.2

This issue is probably really obvious, but I can't get it to work, any help would be appreciated. Thanks!

**Comment by crobibero** [comment]
The url is just be `https://gotify.domain.de`
