### ISSUE TITLE
Repository issue

### ISSUE THREAD

**Issue by bixtool** [crobibero/jellyfin-plugin-webhook#4]
I would like to install this plugin and I understand I need to add your repository. Your Gotify plugin was available in Jellyfin and works perfectly but is a little limited. How do I add a repository to Jellyfin server? All my searches have failed.

**Comment by crobibero** [comment]
Dashboard -> Plugins -> Repositories 
![image](https://user-images.githubusercontent.com/24963659/99464531-9b262900-28f5-11eb-8880-456dac95effa.png)
You can name the repo whatever you would like.
