### ISSUE TITLE
Template files

### ISSUE THREAD

**Issue by bixtool** [crobibero/jellyfin-plugin-webhook#5]
hi,
I've installed your plugin but I'm not quite sure how or where to use the templates files. Are they needed? the plugin has what appears to be template code window. can you explain a basic configuration?

Thanks

**Comment by crobibero** [comment]
If you want to use the provided template, all you need to do is paste the template contents into the template code window.

**Comment by bixtool** [comment]
Working now thanks. Strange it failed previously when I copied/pasted.  Would it be difficult to embed a tv or movie poster in the notification?

**Comment by crobibero** [comment]
It should already have that set, sometimes scan doesn't complete before the notification is sent out

**Comment by bixtool** [comment]
I see "thumbnail" listed in the template code for Discord, but not in the Gotify code.  Two test episodes for Gotify but no image /poster was displayed as below:

![image](https://user-images.githubusercontent.com/11953215/99920150-2ccdd600-2cfc-11eb-8e5b-296eb6d93414.png)

**Comment by crobibero** [comment]
To me that looks like Jellyfin hadn't finished scanning. This part is what specifies to send an image with the alert
```
{{ServerUrl}}/Items/{{ItemId}}/Images/Primary
```

After 10.7 is released I will go through and enhance the plugin a little

**Comment by bixtool** [comment]
That would be great. Thank you
