### ISSUE TITLE
Repository not found - Likely PEBKAC

### ISSUE THREAD

**Issue by MikeColes** [crobibero/jellyfin-plugin-webhook#6]
While looking at the original Gotify plugin, I came across this repository.

It's quite possibly an issue on my side. I tried adding the repo listed in README.md file. It looks to be forwarded to s3.wasabisys.com. I couldn't get that name to resolve at 8.8.8.8 or 1.1.1.1

https://github.com/crobibero/jellyfin-plugin-webhook/blob/master/README.md#repository---httpsrepocodyrobiberodevmanifestjson

Mostly a heads-up. Thank you for putting out this software.

--
Mike

**Comment by crobibero** [comment]
Thank you for letting me know, I will fix in the coming days

**Comment by crobibero** [comment]
Looks like it’s not just us, hopefully it will start working soon.

https://twitter.com/wasabi_cloud/status/1343672586119622659?s=20

**Comment by MikeColes** [comment]
It looks they just came back online. Thank you for troubleshooting the issue.

**Comment by crobibero** [comment]
I’m just glad it wasn’t something I did 😅
