### ISSUE TITLE
Unicode characters cannot be used in the template

### ISSUE THREAD

**Issue by otonashixav** [crobibero/jellyfin-plugin-webhook#8]
Jellyfin version 10.6.4; plugin version 1.2020.914.1640

The handlebars template does not accept unicode characters. Attempting to use any will output `Uncaught DOMException: String contains an invalid character` in the console, which traces back to this line: https://github.com/crobibero/jellyfin-plugin-webhook/blob/afdbd764f123f863bc35e22b087febb1dbf299d3/Jellyfin.Plugin.Webhook/Configuration/Web/config.js#L137

I'm not familiar with js, but think it might need `encodeURIComponent` (and decode later on). 

(I don't see a fix between the version I'm on and latest commit, forgive me if it's already been fixed elsewhere). 

Additionally, the loading circle seems to spin forever until the template is saved again without any offending characters; a seperate issue?

**Comment by crobibero** [comment]
What characters are you trying to use so I can easily replicate?

**Comment by otonashixav** [comment]
My bad. I made a few edits to the template but ultimately trying to insert 🔗 as part of a link name broke it. 

Reproduction steps: 

1. Use the discord template and set everything up, making sure that it works.
2. Insert 🔗 somewhere, like as part of a name of a link. 
3. Press save.

**Comment by crobibero** [comment]
Thank you for providing the character, I will see if I can make some changes to get it working when I have a moment

**Comment by crobibero** [comment]
Fixed by https://github.com/crobibero/jellyfin-plugin-webhook/commit/1bb78e36985a3bb6fdc97b07d9a30c0495b629e5
