### ISSUE TITLE
Quotes in variables do not display correctly in Discord

### ISSUE THREAD

**Issue by otonashixav** [crobibero/jellyfin-plugin-webhook#9]
Jellyfin version 10.6.4; plugin version 1.2020.914.1640

I'm not sure if this has been solved in a later version. I'm not sure if the problem is limited to discord.

This is the overview taken directly from the episode page: 
![image](https://user-images.githubusercontent.com/42372774/105952801-100f9f00-60ad-11eb-85e2-f425e98bd6fd.png)

Using `{{Overview}}` results in: 
![image](https://user-images.githubusercontent.com/42372774/105952261-48fb4400-60ac-11eb-89ac-cbd1c7345f3d.png)
```
{
    "username": "{{Username}}",
    "avatar_url": "{{AvatarUrl}}",
    "content": "",
    "embeds": [
        {
            {{if_equals ItemType 'Season'}}
                "title": "New Season: {{SeriesName}} - {{Name}}",
            {{else}}
                {{if_equals ItemType 'Episode'}}
                    "title": "New Episode: {{SeriesName}} - S{{SeasonNumber00}}E{{EpisodeNumber00}} - {{Name}}",
                {{else}}
                    "title": "New {{ItemType}}: {{Name}} - ({{Year}})",
                {{/if_equals}}
            {{/if_equals}}
            "image":{
                "url": "{{ServerUrl}}/Items/{{ItemId}}/Images/Primary"
            },
            "url": "{{ServerUrl}}/web/index.html#!/details?id={{ItemId}}&serverId={{ServerId}}",
            "color": "{{EmbedColor}}",
            "description": "{{Overview}}",
            "author": {
                "name": "{{Username}}",
                "url": "{{ServerUrl}}",
                "icon_url": "{{AvatarUrl}}"
            }
        }
    ]
}
```

Manually inserting a quote works if you escape it:
![image](https://user-images.githubusercontent.com/42372774/105952280-50225200-60ac-11eb-88f9-9996911ef032.png)
```
            "description": "\"",
```
(the rest is unchanged)

I believe that handlebars is not correctly formatting the quotes.

**Comment by crobibero** [comment]
Fixed in latest update.

Please note- I've updated the templates to fix other issues. (https://github.com/crobibero/jellyfin-plugin-webhook/commit/ebca211e9b77beb9e6b5234def0233c6ec70b2df)

`{{Overview}}` -> `{{{Overview}}}`

Hopefully we can get 10.7 out the door soon so you can use the updated plugin.

Thank you for using and helping test this plugin 😄
